name: petverse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.3.0
  google_maps_flutter: ^2.11.0
  geolocator: ^13.0.3
  url_launcher: ^6.1.14
  google_places_flutter: ^2.1.0
  provider: ^6.1.2
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.17.5
  firebase_core: ^2.32.0
  firebase_storage: ^11.5.1
  location: ^8.0.0
  shared_preferences: ^2.5.3
  geoflutterfire2: ^2.3.15
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/login.png
    - assets/signup.png
    - assets/lostandfound.png
    - assets/petclinic.png
    - assets/essentials.png
    - assets/mating.png
    - assets/adoption.png

  fonts:
    - family: Rubik Bubbles
      fonts:
        - asset: assets/fonts/RubikBubbles-Regular.ttf
